import Head from "next/head";
import { useAuth } from "@/context/auth";
import { login } from "@/lib/auth";
import { useState } from "react";
import { useRouter } from "next/router"; // Next.js のルーターをインポート
import CommonButton from "@/components/uiComponents/Buttons/CommonButton";
import styles from "@/styles/style.module.scss";

export default function Home() {
  const user = useAuth();
  const [waiting, setWaiting] = useState<boolean>(false); // ログイン中かどうかの状態を管理
  const router = useRouter(); // Next.js のルーターを使用

  const signIn = () => {
    setWaiting(true);

    login()
      .then(() => {
        // ログイン成功時に/homeにリダイレクト
        router.push("/home");
        console.log("ログイン成功");
      })
      .catch((error) => {
        console.error(error?.code);
      })
      .finally(() => {
        setWaiting(false);
      });
  };

  return (
    <>
      <Head>
        <title>まちゃろぐ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.inner}>
          <h1 className={styles.title}>まちゃろぐ</h1>
          {user === null && !waiting && (
            <CommonButton text="ログイン" onClick={signIn} />
          )}
        </div>
      </main>
    </>
  );
}
