import Head from "next/head";
import { useAuth } from "@/context/auth";
import { login } from "@/lib/auth";
import { useState } from "react";
import { useRouter } from "next/router"; // Next.js のルーターをインポート
import CommonButton from "@/components/uiComponents/Buttons/CommonButton";
import styles from "@/styles/style.module.scss";
import firebase from "firebase/compat/app";
import { auth, db } from "@/lib/firebase";
import { collection, doc, getDoc, setDoc } from "firebase/firestore"; // Import the necessary Firestore methods

export default function Home() {
  const user = useAuth();
  const [waiting, setWaiting] = useState<boolean>(false); // ログイン中かどうかの状態を管理
  const router = useRouter(); // Next.js のルーターを使用

  const signIn = () => {
    setWaiting(true);

    login()
      .then(() => {
        // Firestoreにユーザーのドキュメントが存在しない場合は、ドキュメントを作成
        auth.onAuthStateChanged(async (user) => {
          if (user) {
            var userDoc = await getDoc(doc(collection(db, "users"), user.uid));
            if (!userDoc.exists) {
              await setDoc(userDoc.ref, {
                screen_name: user.uid,
                display_name: "名無しさん",
                created_at: firebase.firestore.FieldValue.serverTimestamp(),
              });
            }
          }
        });
        router.push("/home");
      })
      .catch((error) => {
        console.error(error?.code);
      })
      .finally(() => {
        setWaiting(false);
      });
  };

  return (
    <>
      <Head>
        <title>TITLE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.inner}>
          <h1 className={styles.title}>TITLE</h1>
          {user === null && !waiting && (
            <CommonButton text="ログイン" onClick={signIn} />
          )}
        </div>
      </main>
    </>
  );
}
